# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a70eb85942f6ae6ff8be59c9b82a7008575966ed89d517f6b93cb3c7ba31ee6d8610033bb0c63874751f8bd9b739d83d2a0604289d77850a8ff152407cc88c4

test:
  secret_key_base: 4a5f2ae6c0d068206494dc0126aaae064f23cfb96f3c16b682d8ee2ca63f94e58f51e0e787394c0777b44b3c54716f3a8dbec0c4e206cc373cd8e7c660dd172c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
